name: linter
on:
  pull_request:
jobs:
  pysen:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - run: curl -sSL https://install.python-poetry.org | python -
      - run: echo "$HOME/.poetry/bin" >> $GITHUB_PATH
      - run: cd job
      - run: poetry install --no-interaction
      - run: make lint
