name: python-ci
on:
  pull_request:
jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install poetry
        run: |
          curl -sSL https://install.python-poetry.org | python -
          echo "$HOME/.poetry/bin" >> $GITHUB_PATH
      - name: Install dependencies
        run: cd job && poetry install --no-interaction
      - name: Run linter
        run: cd job && make lint
  pytest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install poetry
        run: |
          curl -sSL https://install.python-poetry.org | python -
          echo "$HOME/.poetry/bin" >> $GITHUB_PATH
      - name: Install dependencies
        run: cd job && poetry install --no-interaction
      - name: Create dot env file
        run: |
          touch .env
          echo "FOO=${{ secrets.API_KEY }}" >> .env
          echo "FOO=${{ secrets.CHANNEL_ID}}
      - name: Run tests
        run: cd job && make test