name: rails-ci
on:
  pull_request:
    paths:
      - "app/**"
jobs:
  minitest:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: app
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2.2
      - name: Install sqlite3
        run: |
          sudo apt install libsqlite3-dev
          gem install sqlite3 -v '1.4.2' --source 'https://rubygems.org/'
          dpkg -L libsqlite3-dev
      - name: Cache gems
        uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-
      - name: Install dependencies
        run: bundle install
      - name: Run tests
        run: rails test
